### PR TITLE
Added Dictionary to store hurricane names

### PR DESCRIPTION
**Pull request by rishabmenon**
Hi! 
I've created a new simple` dictionary.py` file. It contains two separate dictionaries h_2019 & h_2018 which stores hurricane names for the years 2019 & 2018 respectively as requested.
Once you give a green signal on this, I would be happy to create dictionaries for other years as well! :)

### CODE REVIEW

**Review by WxBDM — CHANGES_REQUESTED** [review]
Looks good! Once you have the rest of them in there, I'll go ahead and merge changes.

**Comment by rishabmenon** [comment]
Okay great! Sounds good! Will work on it! :)

**Comment by rishabmenon** [comment]
Hi,
I've added the rest of the dictionaries for the remaining years ( 2017-2008).
Thanks!

**Comment by WxBDM** [comment]
Everything looks good. Great job! One thing I didn't foresee is having 2 of the same name in the same year in both the Atlantic and EPAC basins. 2016 has this scenario, so we'll have to figure out a way around this. I'll leave this open if you want to work towards a solution.

**Pull request merged**
